[package]
name = "raytraced_spheres"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
gambetta_raytracer = { path = "../gambetta_raytracer" }
sdl3 = "0.16.2"
image = "0.25"

