[package]
name = "gambetta_raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
smallvec = "1.15.1"
rayon = "1.11.0"

[dev-dependencies]
test_utils = { path = "../test_utils" }